import Navbar from "./Components/Navbar/Navbar";
import Home from "./Components/Home/Home";
import "./globals.css";
import About from "./Components/About/About";
import Experience from "./Components/Experience/Experience";




export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#171d32] min-h-screen w-full" >

        <Navbar />
        <Home />
        <About />
        <Experience />

        {children}
      </body>
    </html>
  );
}
